server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  bulkhead:
    instances:
      dafault:
        max-concurrent-calls: 10
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s
  retry:
    instances:
      foo-bar:
        max-attempts: 5
spring:
  application:
    name: user-service
  kafka:
    bootstrap-servers:
    - kafka:9092
springdoc:
  api-docs:
    path: /user-service/v3/api-docs
management:
  tracing:
    sampling:
      probability: 1.0