server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:

        - id: address-service
          uri: lb://address-service
          predicates:
          - Path=/api/v1/address-service/process/addresses/**, /address-service/v3/api-docs

        - id: address-service-consumer
          uri: lb://address-service-consumer
          predicates:
          - Path=/api/v1/address-service/system/addresses/**

        - id: auth-service
          uri: lb://auth-service
          predicates:
          - Path=/auth-service/**

        - id: user-service
          uri: lb://user-service
          predicates:
          - Path=/api/v1/user-service/process/users/**, /user-service/v3/api-docs

        - id: user-service-consumer
          uri: lb://user-service-consumer
          predicates:
          - Path=/api/v1/user-service/system/users/**

        - id: product-service
          uri: lb://product-service
          predicates:
          - Path=/api/v1/product-service/process/products/**, /product-service/v3/api-docs

        - id: product-service-consumer
          uri: lb://product-service-consumer
          predicates:
          - Path=/api/v1/product-service/system/products/**

        - id: openapi
          uri: lb://api-gateway
          predicates:
          - Path=/v3/api-docs/**
          filters:
          - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
management:
  tracing:
    sampling:
      probability: 1.0