server:
  port: 8401
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: address-service-consumer
  datasource:
    url: jdbc:postgresql://localhost:5435/address_service
    username: address_user
    password: 123
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update
# springdoc:
#   api-docs:
#     path: /user-consumer-service/v3/api-docs
management:
  tracing:
    sampling:
      probability: 1.0
resilience4j:
  bulkhead:
    instances:
      dafault:
        max-concurrent-calls: 10
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s
